/*
Even Fibonacci numbers
Project Euler - Problem 2 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var limit = 4000000;
var Fibonacci = [1, 2];
var sum = 0;

while (Fibonacci[Fibonacci.length - 1] < limit) {
    Fibonacci.push(Fibonacci[Fibonacci.length - 2] + Fibonacci[Fibonacci.length - 1]);
}
Fibonacci.pop(Fibonacci[Fibonacci.length - 1]);


for (i = 0; i < Fibonacci.length; i++) {
    if (Fibonacci[i] % 2 === 0) {
        sum += Fibonacci[i];
    }
}

console.log(sum);